version: "3"
services:
  accounts:
    build: "./accounts"
    depends_on:
      - accounts-db
    environment:
      - DB_URI=mysql://root:password@accounts-db/db?charset=UTF8
    volumes:
      - ./accounts:/app

  accounts-db:
    image: "mysql:latest"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
    ports:
      - 0.0.0.0:7200:3306
